version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - C:\\Users\\xazak\\Documents\\LPOO\\Docker-volumes\\mysql57:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2968239ms
      MYSQL_DATABASE: salud
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db